### ISSUE TITLE
Port qca-qt4 to katie.

### ISSUE THREAD

**Issue by FredBezies** [fluxer/katana#22]
If you try to build qca-qt4 using katie, it won't work, related to missing qmake-qt4 executable.

```
CMake Deprecation Warning at CMakeLists.txt:18 (cmake_policy):
  The OLD behavior for policy CMP0042 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


CMake Error at /usr/share/cmake-3.16/Modules/FindQt4.cmake:1314 (message):
  Found unsuitable Qt version "5.14.1" from /usr/bin/qmake, this code
  requires Qt 4.x
Call Stack (most recent call first):
  CMakeLists.txt:76 (find_package)


-- Configuring incomplete, errors occurred!
```

**Comment by fluxer** [comment]
Sorry for the late reply,

There is [KATIE_BUILD](https://github.com/fluxer/qca/blob/master/CMakeLists.txt#L43) option for it. Some of the software that is maintained as part of the Katana project, e.g. QCA, requires `KATIE_BUILD=ON` option passed as argument because it can be used as drop-in replacement for the original software thus it defaults to `OFF`.

I've personally packaged QCA for Arch in the past by borrowing package files for the said software and applying minor changes such as changing the sources array and the directory name where the source is located and that is why the options still default to `OFF`.

You can see which software require such argument to be passed by looking at my [core](https://github.com/fluxer/core/tree/master/katana) repository however in some cases it does not prefix/suffix the software that is usually done to avoid conflicts with either Qt4 or Qt5 so if you package for Katie specificly and for a host that may have Qt4/Qt5 installed you may have to do so.

Basicly, there are two ways to package both Katie and Katana. Which one you choose depends on you but you have to consider all of the possibilities, make sure you follow packaging guidelines ( e.g. https://wiki.gentoo.org/wiki/Qt for Gentoo) where possible (I do not in all cases and I have my own reasons for it) and get to know the software you are packaging.

Cheers!

**Comment by FredBezies** [comment]
Ok. Thanks for your answer. For now, I'll do a PKGBUILD cleanup. Within a day or two, I will try a full katana build based on Katie only.

**Comment by fluxer** [comment]
Sounds good.

Cheers!

**Comment by FredBezies** [comment]
:)
