### ISSUE TITLE
Arch: "/usr/sbin exists in filesystem"

### ISSUE THREAD

**Issue by Starcr0ss** [fluxer/katana#37]
Hi, I was trying to install Katana on an Arch VM to see if it works and it appears there is an issue with the katana-workspace package. When I run `makepkg --install`, pacman complains that 
```
katana-workspace: /usr/sbin exists in filesystem (owned by filesystem)
katana-workspace: /usr/share/dbus-1/services/org.kde.kglobalaccel.service exists in filesystem (owned by kglobalaccel)
```
I was able to get rid of the kglobalaccel issue by renaming the conflicting file to add .old, but I can't change an entire directory that has important files in it.

**Comment by Starcr0ss** [comment]
It appears that running `sudo pacman -U --overwrite /usr/sbin katana-workspace` allows the package to install but this is less than ideal.

**Comment by fluxer** [comment]
The top line on [this page](https://github.com/fluxer/katana/wiki/Building-and-installing#warning) warns about the possible conflicts, it is something I am aware for quite some time. Fixing the conflicts is somewhat possible but something I have not looked into yet, not sure if I should even. For example the `xdg-open` script calls `kde-open` meaning changing the basename of some programs Katana provides is likely to break things rather than fix them.

**Comment by fluxer** [comment]
Regardless of the possible conflicts the project keeps rocking it for years, let me know if you find a fix for what you are describing here. Meanwhile, things will get rewritten and the value of this issue decreases. For example:
https://github.com/fluxer/kde-workspace/commit/31afa6c691776e3688b1caf3e3327d54d933f15b
https://github.com/fluxer/kde-workspace/commit/3ad56ec0b3be126129039ea6ce5b89045a39569c

Closing.

**Comment by MrReplikant** [comment]
I don't know about the arch linux or freebsd side, but i definitely have an idea of how I can fix this for Debian. I am going to fork the repo and test a fix of my own. I will keep you updated.
