### ISSUE TITLE
Feature Request: Make it clear how to get "Katie"

### ISSUE THREAD

**Issue by Starcr0ss** [fluxer/katana#38]
When I was first trying to set up the build for Katana on Arch, I used the PKGBUILD files, and would constantly get bugged by issues of not having Katie as a dependency. I would like to propose that this requirement is better communicated in how to get it, or to bundle it in the katana repo. Also, it would be helpful if the README file in the root of this repo explained how to install Katana on each distro.

**Comment by fluxer** [comment]
Hi,

there is a [wiki page with information how to build, install and setup Katana](https://github.com/fluxer/katana/wiki/Building-and-installing#building-and-installing-sub-projects). There is a [link to Katie](https://github.com/fluxer/katana/wiki/Building-and-installing#build-time) on that page. On the Katie wiki there is info, people just have to read it.

I will not put info in the README about installing. Usually projects use INSTALL, BUILD or some other file to hint people how to do that but I will not add such files - I prefer the wiki because it allows me to make some fancy stuff like tables and I can edit it from anywhere, include my phone (have done so in the past). There was a time editing repository files was not a thing here and I am sticking with the wiki.

I am also not going to put info about how to install and use it on every distribution, that would be overkill and may require frequent updates due to the nature of the distributions. If you look at [distrowatch.com](https://distrowatch.com/) you will find that there are many distributions. Adding info about some of the top-10 however seems reasonable, already done for Debian and possibly its derivatives (depending on how much the distributions diverge) including files to make packages.

The main repository is not supposed to host or bundle the other repositories, especially Katie. The thing is Katana is a desktop environment project while Katie is a toolkit that Katana is build upon. Even tho the projects are tide together they are about very different things and I believe it should stay so, atleast for now.

Cheers!

**Comment by fluxer** [comment]
Closing due to https://github.com/fluxer/kdelibs/commit/08660485c4a641b3b8a66ae4fbfd72c78774a616 and the information how to install it being there.
