### ISSUE TITLE
Unable to build Katana, problems with OSDN

### ISSUE THREAD

**Issue by Starcr0ss** [fluxer/katana#40]
Hi, I am trying to build Katana in a VM and when I run the "build.sh" script I get the following:
`fatal: repository 'https://scm.osdn.net/gitroot/kde/Katie/ariya-icons.git/' not found`
Another thing I noted is that, when I click the link to the OSDN version of Katana's source code at https://osdn.net/projects/kde , I get a "504 Gateway Time-out".
What can I do so I can fetch the files I need to build KDE? Is OSDN breaking down?

**Comment by fluxer** [comment]
Hi,

The base URL was corrected, building via the `build.sh` script should work now.

About OSDN - apparently it does have issues from time to time but none of my concern. I use it to host the repositories (which are hosted on multiple sites) and that's about it. I'm also thinking about moving the wiki to git repository or something like that so that it can be edited and uploaded anywhere but that is to be decided and done after the next release at which point the project will become independent of any online service.

**Comment by Starcr0ss** [comment]
> Hi,
> 
> The base URL was corrected, building via the `build.sh` script should work now.

Just gave it another try and it works perfectly. Am currently building Katana rn. Thanks for your quick response and fix!

**Comment by fluxer** [comment]
No problem!

Cheers!
